eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost

server:
  port: 8080
  max-http-header-size: 100000
spring:
  application:
    name: GATEWAY_SERVICE
  jackson:
    default-property-inclusion: NON_NULL
      
  cloud:
    gateway:
      routes:
      - id: AuthenticationService
        uri: http://localhost:8081
        predicates:
        - Path=/api/v1/auth/**
        filters:
        - AuthFilter
      - id: UserService
        uri: http://localhost:8082
        predicates:
        - Path=/api/v1/users/**
        filters:
        - AuthFilter
      - id: ProductService
        uri: http://localhost:8083
        predicates:
        - Path=/api/v1/products/**
       
jwt:
 secret: myjwtsecret




